-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 22:08:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`Budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Budget` (
  `BudgetID` INT NOT NULL,
  `money` INT NOT NULL,
  PRIMARY KEY (`BudgetID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`FamilyMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`FamilyMember` (
  `FamilyMemberID` INT NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `Budget_BudgetID` INT NOT NULL,
  PRIMARY KEY (`FamilyMemberID`),
  INDEX `fk_FamilyMember_Budget1_idx` (`Budget_BudgetID` ASC) VISIBLE,
  CONSTRAINT `fk_FamilyMember_Budget1`
    FOREIGN KEY (`Budget_BudgetID`)
    REFERENCES `database`.`Budget` (`BudgetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`PersonalAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`PersonalAccount` (
  `ID` INT NOT NULL,
  `FamilyMemberID` INT NOT NULL,
  `amount` INT NOT NULL,
  INDEX `fk_PersonalAccount_FamilyMember1_idx` (`FamilyMemberID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_PersonalAccount_FamilyMember1`
    FOREIGN KEY (`FamilyMemberID`)
    REFERENCES `database`.`FamilyMember` (`FamilyMemberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Operations` (
  `OperationsID` INT NOT NULL,
  `amount` INT NOT NULL,
  `direction` TINYINT NOT NULL,
  `PersonalAccount_ID` INT NOT NULL,
  `Budget_BudgetID` INT NOT NULL,
  PRIMARY KEY (`OperationsID`),
  INDEX `fk_Operations_PersonalAccount1_idx` (`PersonalAccount_ID` ASC) VISIBLE,
  INDEX `fk_Operations_Budget1_idx` (`Budget_BudgetID` ASC) VISIBLE,
  CONSTRAINT `fk_Operations_PersonalAccount1`
    FOREIGN KEY (`PersonalAccount_ID`)
    REFERENCES `database`.`PersonalAccount` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operations_Budget1`
    FOREIGN KEY (`Budget_BudgetID`)
    REFERENCES `database`.`Budget` (`BudgetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`story` (
  `StoryID` INT NOT NULL,
  `PersonalAccount_ID` INT NOT NULL,
  `transaction` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  INDEX `fk_story_PersonalAccount1_idx` (`PersonalAccount_ID` ASC) VISIBLE,
  PRIMARY KEY (`StoryID`),
  CONSTRAINT `fk_story_PersonalAccount1`
    FOREIGN KEY (`PersonalAccount_ID`)
    REFERENCES `database`.`PersonalAccount` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
