"""empty message

Revision ID: 05fd7809dbc1
Revises: 
Create Date: 2020-12-08 23:07:17.596128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05fd7809dbc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FamilyMember',
    sa.Column('FamilyMemberID', sa.INTEGER(), nullable=False),
    sa.Column('UserName', sa.VARCHAR(length=45), nullable=True),
    sa.Column('FirstName', sa.VARCHAR(length=45), nullable=True),
    sa.Column('LastName', sa.VARCHAR(length=45), nullable=True),
    sa.Column('email', sa.VARCHAR(length=45), nullable=True),
    sa.Column('password', sa.VARCHAR(length=45), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=45), nullable=True),
    sa.Column('Budget_BudgetID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['Budget_BudgetID'], ['budget.BudgetID'], ),
    sa.PrimaryKeyConstraint('FamilyMemberID')
    )
    op.create_table('PersonalAccount',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('FamilyMemberID', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['FamilyMemberID'], ['FamilyMember.FamilyMemberID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Operations',
    sa.Column('OperationsID', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('direction', sa.BOOLEAN(), nullable=True),
    sa.Column('PersonalAccount_ID', sa.INTEGER(), nullable=True),
    sa.Column('Budget_BudgetID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['Budget_BudgetID'], ['budget.BudgetID'], ),
    sa.ForeignKeyConstraint(['PersonalAccount_ID'], ['PersonalAccount.ID'], ),
    sa.PrimaryKeyConstraint('OperationsID')
    )
    op.create_table('Story',
    sa.Column('StoryID', sa.INTEGER(), nullable=False),
    sa.Column('PersonalAccount_ID', sa.INTEGER(), nullable=True),
    sa.Column('transaction', sa.BOOLEAN(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['PersonalAccount_ID'], ['PersonalAccount.ID'], ),
    sa.PrimaryKeyConstraint('StoryID')
    )
    op.drop_index('fk_Operations_Budget1_idx', table_name='operations')
    op.drop_index('fk_Operations_PersonalAccount1_idx', table_name='operations')
    op.drop_table('operations')
    op.drop_index('fk_story_PersonalAccount1_idx', table_name='story')
    op.drop_table('story')
    op.drop_index('fk_PersonalAccount_FamilyMember1_idx', table_name='personalaccount')
    op.drop_table('personalaccount')
    op.drop_index('fk_FamilyMember_Budget1_idx', table_name='familymember')
    op.drop_table('familymember')
    op.alter_column('budget', 'money',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', 'money',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_table('familymember',
    sa.Column('FamilyMemberID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('UserName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('LastName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('Budget_BudgetID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Budget_BudgetID'], ['budget.BudgetID'], name='fk_FamilyMember_Budget1'),
    sa.PrimaryKeyConstraint('FamilyMemberID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_FamilyMember_Budget1_idx', 'familymember', ['Budget_BudgetID'], unique=False)
    op.create_table('personalaccount',
    sa.Column('ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FamilyMemberID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['FamilyMemberID'], ['familymember.FamilyMemberID'], name='fk_PersonalAccount_FamilyMember1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_PersonalAccount_FamilyMember1_idx', 'personalaccount', ['FamilyMemberID'], unique=False)
    op.create_table('story',
    sa.Column('StoryID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PersonalAccount_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('data', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['PersonalAccount_ID'], ['personalaccount.ID'], name='fk_story_PersonalAccount1'),
    sa.PrimaryKeyConstraint('StoryID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_story_PersonalAccount1_idx', 'story', ['PersonalAccount_ID'], unique=False)
    op.create_table('operations',
    sa.Column('OperationsID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direction', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.Column('PersonalAccount_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Budget_BudgetID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Budget_BudgetID'], ['budget.BudgetID'], name='fk_Operations_Budget1'),
    sa.ForeignKeyConstraint(['PersonalAccount_ID'], ['personalaccount.ID'], name='fk_Operations_PersonalAccount1'),
    sa.PrimaryKeyConstraint('OperationsID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_Operations_PersonalAccount1_idx', 'operations', ['PersonalAccount_ID'], unique=False)
    op.create_index('fk_Operations_Budget1_idx', 'operations', ['Budget_BudgetID'], unique=False)
    op.drop_table('Story')
    op.drop_table('Operations')
    op.drop_table('PersonalAccount')
    op.drop_table('FamilyMember')
    # ### end Alembic commands ###
